(defun add-to-epath (name path)
  (let ((current (getenv name)))
    (if (and current
	     (not (member path (split-string current ":" t))))
	(if (string= current "")
	    (setenv name path)
	  (setenv name (concat path ":" current))))
    (getenv name)))

(when (file-directory-p "/opt/local/bin")
  (add-to-list 'exec-path "/opt/local/bin")
  (add-to-list 'load-path "/opt/local/share/doc/git-core/contrib/emacs")
  (add-to-epath "PATH" "/opt/local/bin")
  (add-to-epath "PATH" "/Library/Tcl/bin")
  (add-to-epath "INFOPATH" "/opt/local/share/info")
  (add-to-epath "MANPATH" "/opt/local/man"))

(setq my-ext-dir "~/.emacs.d/ext")
(add-to-list 'load-path my-ext-dir)

(dolist (d (directory-files my-ext-dir))
  (let ((full-path (concat my-ext-dir "/" d)))
    (when (not (or (string= d ".") (string= d "..")))
      (when (file-directory-p full-path)
	(add-to-list 'load-path full-path)
	(dolist (subd (directory-files full-path))
	  (let ((subd-path (concat full-path "/" subd)))
	    (when (and (or (string= subd "elisp") (string= subd "lisp"))
		       (file-directory-p subd-path))
	      (add-to-list 'load-path subd-path))))))))

(provide 'init-load-path)
